# Don't print a new line at the start of the prompt
add_newline = true

# Replace the "â¯" symbol in the prompt with "âœ "
[character]      # The name of the module we are configuring is "character"
symbol = "âœ "     # The "symbol" segment is being set to "âœ "
error_symbol = "âœ—"
use_symbol_for_status = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[hostname]
format = "âŸª[$hostname]âŸ«($style) in "
ssh_only = true
trim_at = ".companyname.com"
disabled = false

[username]
show_always = true
disabled = false

[jobs]
symbol = "âœ¦ + "
threshold = 0
style = "bold green"

[time]
disabled = false
time_format = "%R"
format = "ï—¯ [$time]($style) "
# utc_time_offset = "-5"
style = "white"

[python]
symbol = "îˆµ "
# style = "bold fg:3"

[battery]
full_symbol = "ğŸ”‹"
charging_symbol = "âš¡ï¸"

[directory]
truncation_length = 8
truncate_to_repo = false
